mod bindings_comparison;

use std::{
    collections::HashMap,
    path::{Path, PathBuf},
};

use clap::Parser;
use sha2::Digest as _;

use crate::bindings_comparison::compare_generated_bindings;

#[derive(clap::Parser)]
struct Cli {
    #[clap(subcommand)]
    command: Commands,
}

#[derive(clap::Subcommand)]
#[allow(clippy::enum_variant_names)]
enum Commands {
    GenerateReferenceBindings(CommandGenerateReferenceBindings),
    DetectStaleGeneratedReferenceBindings(DetectStaleGeneratedReferenceBindings),
    CompareGeneratedBindings(CompareGeneratedBindings),
}

#[derive(clap::Parser)]
struct CommandGenerateReferenceBindings {
    #[clap(long)]
    wrapper: PathBuf,
    #[clap(long)]
    submodule: PathBuf,
    #[clap(long)]
    output: PathBuf,
}

#[derive(clap::Parser)]
struct DetectStaleGeneratedReferenceBindings {
    #[clap(long)]
    wrapper: PathBuf,
    #[clap(long)]
    submodule: PathBuf,
    #[clap(long)]
    bindings: PathBuf,
}

#[derive(clap::Parser)]
struct CompareGeneratedBindings {
    #[clap(long)]
    config: PathBuf,
    #[clap(long)]
    openfx_bindgen_bindings_folder: PathBuf,
    #[clap(long)]
    reference_bindings_file: PathBuf,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    tracing_subscriber::fmt()
        .with_ansi_sanitization(false) // for `prettydiff`
        .init();

    let cli = Cli::parse();

    match cli.command {
        Commands::GenerateReferenceBindings(cmd) => generate_reference_bindings(cmd)?,
        Commands::DetectStaleGeneratedReferenceBindings(cmd) => {
            detect_stale_generated_reference_bindings(cmd)?
        }
        Commands::CompareGeneratedBindings(cmd) => compare_generated_bindings(cmd)?,
    }

    Ok(())
}

fn generate_reference_bindings(
    cmd: CommandGenerateReferenceBindings,
) -> Result<(), Box<dyn std::error::Error>> {
    let openfx_submodule_hash = get_submodule_hash(&cmd.submodule)?;

    let wrapper_content = std::fs::read_to_string(&cmd.wrapper)?;

    let wrapper_sha256 = sha2::Sha256::digest(wrapper_content.as_bytes());
    let wrapper_sha256 = hex::encode(wrapper_sha256);

    let bindings = bindgen::Builder::default()
        .header_contents("wrapper.h", &wrapper_content)
        .generate_cstr(true)
        .generate()?;

    let mut output = format!("// openfx_submodule_hash={openfx_submodule_hash}\n");
    output += &format!("// wrapper_sha256={wrapper_sha256}\n");
    output += &bindings.to_string();

    std::fs::write(&cmd.output, &output)?;

    Ok(())
}

fn detect_stale_generated_reference_bindings(
    cmd: DetectStaleGeneratedReferenceBindings,
) -> Result<(), Box<dyn std::error::Error>> {
    let openfx_submodule_hash = get_submodule_hash(&cmd.submodule)?;

    let wrapper_content = std::fs::read_to_string(&cmd.wrapper)?;

    let wrapper_sha256 = sha2::Sha256::digest(wrapper_content.as_bytes());
    let wrapper_sha256 = hex::encode(wrapper_sha256);

    let bindgen_version = get_bindgen_version()?;
    let Some(bindgen_version) = bindgen_version.strip_prefix("=") else {
        return Err(format!(
            "Expected bindgen version to be pinned (e.g., `=123.456.789`) but found `{}`.",
            bindgen_version
        )
        .into());
    };

    let expected_first_lines = [
        format!("// openfx_submodule_hash={openfx_submodule_hash}"),
        format!("// wrapper_sha256={wrapper_sha256}"),
        format!("/* automatically generated by rust-bindgen {bindgen_version} */"),
    ]
    .join("\n");

    let bindings = std::fs::read_to_string(&cmd.bindings)?;
    let actual_first_lines = bindings
        .lines()
        .take(expected_first_lines.lines().count())
        .collect::<Vec<_>>()
        .join("\n");

    if expected_first_lines == actual_first_lines {
        return Ok(());
    }

    tracing::error!(
        "Stale generated reference bindings detected:\n{}",
        prettydiff::diff_lines(&expected_first_lines, &actual_first_lines)
    );

    Err("Stale generated reference bindings detected.".into())
}

fn get_submodule_hash(submodule_path: &Path) -> Result<String, Box<dyn std::error::Error>> {
    let openfx_submodule_hash_output = std::process::Command::new("git")
        .args(["rev-parse", &format!("HEAD:{}", submodule_path.display())])
        .output()?;
    if !openfx_submodule_hash_output.status.success() {
        return Err(format!(
            "Failed to execute `git rev-parse HEAD:{}`. exit status: {:}",
            submodule_path.display(),
            openfx_submodule_hash_output.status
        )
        .into());
    }
    let openfx_submodule_hash = String::from_utf8(openfx_submodule_hash_output.stdout)?;
    let openfx_submodule_hash = openfx_submodule_hash.trim();

    Ok(openfx_submodule_hash.to_string())
}

fn get_bindgen_version() -> Result<String, Box<dyn std::error::Error>> {
    let cargo_toml = include_str!("../Cargo.toml");

    #[derive(serde::Deserialize)]
    struct CargoToml {
        dependencies: HashMap<String, CargoTomlDependency>,
    }
    #[derive(serde::Deserialize)]
    #[serde(untagged)]
    enum CargoTomlDependency {
        Version(String),
        Object { version: String },
    }

    let cargo_toml: CargoToml = toml::from_str(cargo_toml)?;
    let dep_bindgen = cargo_toml
        .dependencies
        .get("bindgen")
        .ok_or("Dependency `bindgen` is missing from `Cargo.toml`.")?;
    let bindgen_version = match dep_bindgen {
        CargoTomlDependency::Version(v) => v,
        CargoTomlDependency::Object { version } => version,
    };

    Ok(bindgen_version.to_string())
}
